apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: datanode
  name: datanode
  namespace: graylog
spec:
  serviceName: "headless-datanode"  # Headless service name required by StatefulSet
  replicas: 3 # Modify replicas as needed
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      restartPolicy: Always
      initContainers:
      - name: wait-for-mogodb
        image: busybox
        command: ["sh", "-c", "until nc -z mongodb 27017; do echo Waiting for mongodb availability; sleep 1; done;"]
      containers:
      - name: datanode
        image: graylog/graylog-datanode:6.1.10
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HEADLESS_SERVICE_NAME
          value: "headless-datanode" # If you change the headless service name, update this value
        - name: GRAYLOG_DATANODE_NODE_ID_FILE
          value: "/var/lib/graylog-datanode/node-id"
        - name: GRAYLOG_DATANODE_MONGODB_URI
          value: "mongodb://mongodb:27017/graylog"
        - name: GRAYLOG_DATANODE_PASSWORD_SECRET
          valueFrom:
            secretKeyRef:
              name: graylog-password-secret
              key: GRAYLOG_PASSWORD_SECRET
        - name: GRAYLOG_DATANODE_NODE_NAME
          value: "$(POD_NAME).$(HEADLESS_SERVICE_NAME).$(NAMESPACE).svc.cluster.local"
        ports:
        - name: datanode-api
          containerPort: 8999
        - name: port-9200
          containerPort: 9200
        - name: port-9300
          containerPort: 9300
        volumeMounts:
        - name: graylog-datanode
          mountPath: /var/lib/graylog-datanode
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "3Gi"
      volumes:
      - name: graylog-entrypoint
        configMap:
          name: graylog-entrypoint-cm
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: graylog-datanode
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: datanode
  name: datanode
  namespace: graylog
spec:
  ports:
  - name: datanode-api
    port: 8999
    protocol: TCP
    targetPort: 8999
  - name: port-9200
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: port-9300
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: datanode
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: headless-datanode
  namespace: graylog
  labels:
    app: datanode
spec:
  ports:
  - name: datanode-api
    port: 8999
  - name: port-9200
    port: 9200
  - name: port-9300
    port: 9300
  clusterIP: None
  selector:
    app: datanode
