apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb
  namespace: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      hostname: mongodb
      volumes:
      - name: mongodb-data
        emptyDir: {}
      - name: mongodb-config
        emptyDir: {}
      restartPolicy: Always
      containers:
      - image: mongo:8.0
        name: mongo
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data
        - mountPath: /data/configdb
          name: mongodb-config
        ports:
        - containerPort: 27017
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb
  namespace: graylog
spec:
  ports:
  - port: 27017
    nodePort: 32017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  type: NodePort
status:
  loadBalancer: {}
