apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: graylog
spec:
  serviceName: "mongodb"
  replicas: 1 # Increase replicas as needed
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      hostname: mongodb
      restartPolicy: Always
      containers:
      - image: mongo:8.0
        name: mongo
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data
        - mountPath: /data/configdb
          name: mongodb-config
        ports:
        - containerPort: 27017
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 4Gi # Set as much storage as needed
  - metadata:
      name: mongodb-config
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 4Gi # Set as much storage as needed
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb
  namespace: graylog
spec:
  ports:
  - port: 27017
    nodePort: 32017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: headless-mongodb
  namespace: graylog
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongodb
  clusterIP: None
  selector:
    app: mongodb
